### ISSUE TITLE
Crontab for weather data puling

### ISSUE THREAD

**Issue by agryaznov** [Kosteron/Conky#1]
Hi there. Many thanks for your scripts, they helped me much to understand conky better and to tune it for my needs. 

A suggestion: wouldn't it be better practice to:
1. move that weather data pulling schedule to a crontab instead of `sleep 600` inside infinite while loop?
  https://github.com/Kosteron/Conky/blob/fb1b127fa6edf52a962b44e1c2063266d3330b1e/conky_weather/weather-pull.sh#L6
2. increase the pulling interval to at least once an hour
    + I don't think it really makes sense to pull weather forecast every 10 mins
    + Meanwile wttr.in has limited number of queries to the weather service. So I think It wouldn't be considered a good practice to waste its limits with unnecessary frequent requests. @chubin what do you think?

Thanks!

**Comment by chubin** [comment]
It is ok from wttr.in side, because only the upstream capacity is limited, and the data is cached, so 10-min interval queries are harmless.

Replacing loop + sleep with a cron entry has additional maintenance burden (just imagine that for each script with some loop+sleep loop in the system you have a crontab entry), and I would not recommend to do it unless there is some generalized approach for execution of repetitive tasks in the project anyway

**Comment by agryaznov** [comment]
Well, sounds reasonably. Thanks a lot, closing this one
